name: Deploy Nginx to DO Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ngx-nginx-proxy .

      - name: Copy files to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/ngx-nginx-proxy"

      - name: SSH and restart Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ngx-nginx-proxy
            docker build -t ngx-nginx-proxy .
            docker stop nginx || true
            docker rm nginx || true
            docker run -d --name nginx -p 80:80 ngx-nginx-proxy
            sed -i 's/proxy_pass http:\/\/api-server:3000;/proxy_pass http:\/\/localhost:3000;/' docker/nginx.conf
            docker restart nginx